In [7]:
# ===========================================================================================
# 1. Importação das Bibliotecas
# ===========================================================================================   

import pandas as pd 
import numpy as np

# ===========================================================================================
# 2. Carregamento dos Dados
# ===========================================================================================   
df_vendas = pd.read_csv("vendas_tech.csv", encoding="latin1", sep=",", low_memory=False)
df_gerentes = pd.read_excel("gerentes_lojas.xlsx")

# ===========================================================================================
# 3. Limpeza e Preparação dos Dados
# ===========================================================================================

#Corrige problemas de codificação dos nomes das lojas
df_vendas["Loja"] = (
    df_vendas["Loja"]
    .str.encode("latin1")
    .str.decode("utf-8")
)

#Cria uma cópia do dataframe de vendas para análise
# e remove uma coluna "Data_Base" que não será utilizada na análise
df_analise = df_vendas.drop(columns=["Data_Base"]).copy()

#Preenche valores ausentes na coluna "Loja"
df_analise["Loja"] = df_analise["Loja"].fillna("Online")

#Remove espaços antes e depois do texto
df_analise["Loja"] = df_analise["Loja"].str.strip()

#Padroniza a escrita dos nomes das lojas
df_analise["Loja"] = df_analise["Loja"].str.title()

#Converte a coluna "Data" para o formato datetime
df_analise["Data"] = pd.to_datetime(df_analise["Data"], format = "%Y-%m-%d")

#Remove pedido duplicados
df_analise = df_analise.drop_duplicates(subset=["ID_Pedido"])

#============================================================================================
#4. Inpeção dos Dados
#============================================================================================

display(df_analise.head())

display(df_analise.info())

display(df_analise.describe())

display(df_analise.isnull().sum())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100000 non-null  int64
 1   Data            100000 non-null  datetime64[ns]
 2   Loja            100000 non-null  object
 3   Produto         100000 non-null  object
 4   Preco_Unitario  100000 non-null  float64
 5   Qtd             100000 non-null  int64
 6   Cliente         100000 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 6.1+ MB

None

,ID_Pedido,Data,Preco_Unitario,Qtd
count,100000.000000,100000,100000.000000,100000.000000
mean,50000.500000,2023-12-30 05:20:06.720000,1999.780100,1.499020
min,1.000000,2023-01-01 00:00:00,40.000000,1.000000
25%,25000.750000,2023-06-29 00:00:00,120.000000,1.000000
50%,50000.500000,2023-12-29 00:00:00,1200.000000,1.000000
75%,75000.250000,2024-06-30 00:00:00,3200.000000,1.000000
max,100000.000000,2024-12-30 00:00:00,5500.000000,10.000000
std,28867.657797,NaN,1840.918232,1.241771

ID_Pedido         0
Data              0
Loja              0
Produto           0
Preco_Unitario    0
Qtd               0
Cliente           0
dtype: int64

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
90705,90706,2023-10-21,Porto Alegre,Notebook Dell,3500.0,2,Cliente_20412,NaN
95084,95085,2023-09-27,RIO DE JANEIRO,Teclado MecÃ¢nico,250.0,1,Cliente_12872,NaN
35749,35750,2024-10-20,Curitiba,Smartphone Samsung,2200.0,1,Cliente_5973,NaN
70397,70398,2023-11-01,NaN,Notebook HP,3200.0,1,Cliente_28646,NaN
58225,58226,2023-12-31,Recife,Teclado MecÃ¢nico,250.0,1,Cliente_15938,NaN
59370,59371,2024-09-27,Belo Horizonte,Teclado MecÃ¢nico,250.0,10,Cliente_2474,NaN
96656,96657,2023-03-15,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_25721,NaN
90621,90622,2024-12-12,Curitiba,Mouse Gamer,120.0,1,Cliente_23526,NaN
67210,67211,2023-06-02,Salvador,Notebook Dell,3500.0,1,Cliente_6304,NaN
46463,46464,2023-04-15,Curitiba,Teclado MecÃ¢nico,250.0,1,Cliente_29089,NaN
4848,4849,2023-09-15,Recife,Teclado MecÃ¢nico,250.0,1,Cliente_11268,NaN
39430,39431,2024-10-20,Belo Horizonte,"Monitor 27""",1200.0,1,Cliente_22167,NaN
87376,87377,2023-09-08,Recife,Mouse Gamer,120.0,1,Cliente_8925,NaN
54806,54807,2024-11-27,Salvador,Notebook HP,3200.0,1,Cliente_22919,NaN
65290,65291,2023-08-17,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_1025,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  object
 2   Loja            98099 non-null   object
 3   Produto         100100 non-null  object
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  object
 7   Data_Base       1 non-null       object
dtypes: float64(1), int64(2), object(5)
memory usage: 6.1+ MB

None

           ID_Pedido  Preco_Unitario            Qtd
count  100100.000000   100100.000000  100100.000000
mean    50004.810180     2000.204595       1.499101
std     28866.872543     1841.050733       1.241605
min         1.000000       40.000000       1.000000
25%     25008.750000      120.000000       1.000000
50%     50004.500000     1200.000000       1.000000
75%     75002.250000     3200.000000       1.000000
max    100000.000000     5500.000000      10.000000

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205
99999,100000,2024-06-15,Curitiba,Teclado MecÃ¢nico,250.0,1,Cliente_12237

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100000 non-null  int64
 1   Data            100000 non-null  datetime64[ns]
 2   Loja            100000 non-null  object
 3   Produto         100000 non-null  object
 4   Preco_Unitario  100000 non-null  float64
 5   Qtd             100000 non-null  int64
 6   Cliente         100000 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 6.1+ MB

None

In [2]:
df_analise['Faturamento'] = df_analise['Qtd'] * df_analise['Preco_Unitario']

df_analise['Forma_de_Venda'] = np.where(df_analise['Loja'] == 'Online', 'Online', 'Presencial')


display(df_analise['Loja'].unique())

display(df_analise)

dic_regioes = {
    'São Paulo': 'Sudeste',
    'Belo Horizonte': 'Sudeste',
    'Online': 'Online',
    'Rio De Janeiro': 'Sudeste',
    'Salvador': 'Nordeste',
    'Recife': 'Nordeste',
    'Curitiba': 'Sul',
    'Porto Alegre': 'Sul'
}
df_analise['Regiao'] = (df_analise['Loja'].map(dic_regioes)
.fillna('Não informada'))
display(df_analise)
display(df_analise.isna().sum())

array(['São Paulo', 'Belo Horizonte', 'Online', 'Rio De Janeiro',
       'Salvador', 'Recife', 'Curitiba', 'Porto Alegre'], dtype=object)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Presencial
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Presencial
...,...,...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732,240.0,Presencial
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058,40.0,Presencial
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864,4400.0,Presencial
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205,5500.0,Presencial
99999,100000,2024-06-15,Curitiba,Teclado MecÃ¢nico,250.0,1,Cliente_12237,250.0,Presencial

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Regiao
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial,Sudeste
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Presencial,Sudeste
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0,Online,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Sudeste
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732,240.0,Presencial,Sudeste
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058,40.0,Presencial,Sudeste
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864,4400.0,Presencial,Sul
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205,5500.0,Presencial,Sul
99999,100000,2024-06-15,Curitiba,Teclado MecÃ¢nico,250.0,1,Cliente_12237,250.0,Presencial,Sul

ID_Pedido         0
Data              0
Loja              0
Produto           0
Preco_Unitario    0
Qtd               0
Cliente           0
Faturamento       0
Forma_de_Venda    0
Regiao            0
dtype: int64

In [3]:
df_analise = df_analise.sort_values(by='Data')
df_analise = df_analise.reset_index(drop=True)

display(df_analise)

#loja = df_analise.loc[3, 'Loja']
#produto = df_analise.loc[3, 'Produto']
#cliente = df_analise.loc[3, 'Cliente']
#print(loja, produto, cliente)
#print(df_analise)

df_vendas_sp = df_analise[df_analise['Loja'] == 'São Paulo']
#df_vendas_sp.to_csv('Vendas_SP.csv', index=False, encoding='utf-8-sig')
df_vendas_2024 = df_analise[df_analise['Data'].dt.year == 2024]
                      
#display(df_vendas_sp)
display(df_vendas_2024)


#exportar vendas de 2024

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Regiao
0,34750,2023-01-01,Rio De Janeiro,Notebook HP,3200.0,1,Cliente_9014,3200.0,Presencial,Sudeste
1,13699,2023-01-01,Rio De Janeiro,Teclado MecÃ¢nico,250.0,1,Cliente_24330,250.0,Presencial,Sudeste
2,81394,2023-01-01,Porto Alegre,Teclado MecÃ¢nico,250.0,1,Cliente_9758,250.0,Presencial,Sul
3,251,2023-01-01,São Paulo,Teclado MecÃ¢nico,250.0,3,Cliente_22822,750.0,Presencial,Sudeste
4,77068,2023-01-01,Rio De Janeiro,Notebook Dell,3500.0,1,Cliente_554,3500.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
99995,43207,2024-12-30,Belo Horizonte,Notebook Dell,3500.0,2,Cliente_15893,7000.0,Presencial,Sudeste
99996,3183,2024-12-30,Salvador,Mouse Gamer,120.0,1,Cliente_4075,120.0,Presencial,Nordeste
99997,9461,2024-12-30,Porto Alegre,Teclado MecÃ¢nico,250.0,1,Cliente_22763,250.0,Presencial,Sul
99998,2793,2024-12-30,Salvador,Notebook Dell,3500.0,1,Cliente_24692,3500.0,Presencial,Nordeste
99999,91693,2024-12-30,São Paulo,iPhone 14,5500.0,1,Cliente_17362,5500.0,Presencial,Sudeste

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Regiao
50423,86878,2024-01-01,Salvador,"Monitor 27""",1200.0,1,Cliente_21318,1200.0,Presencial,Nordeste
50424,65074,2024-01-01,Belo Horizonte,Cabo HDMI,40.0,1,Cliente_9100,40.0,Presencial,Sudeste
50425,88699,2024-01-01,Belo Horizonte,"Monitor 27""",1200.0,1,Cliente_16957,1200.0,Presencial,Sudeste
50426,51672,2024-01-01,Porto Alegre,Notebook HP,3200.0,1,Cliente_16437,3200.0,Presencial,Sul
50427,44184,2024-01-01,Curitiba,Cabo HDMI,40.0,1,Cliente_1577,40.0,Presencial,Sul
...,...,...,...,...,...,...,...,...,...,...
99995,43207,2024-12-30,Belo Horizonte,Notebook Dell,3500.0,2,Cliente_15893,7000.0,Presencial,Sudeste
99996,3183,2024-12-30,Salvador,Mouse Gamer,120.0,1,Cliente_4075,120.0,Presencial,Nordeste
99997,9461,2024-12-30,Porto Alegre,Teclado MecÃ¢nico,250.0,1,Cliente_22763,250.0,Presencial,Sul
99998,2793,2024-12-30,Salvador,Notebook Dell,3500.0,1,Cliente_24692,3500.0,Presencial,Nordeste
99999,91693,2024-12-30,São Paulo,iPhone 14,5500.0,1,Cliente_17362,5500.0,Presencial,Sudeste

In [6]:
display(df_analise)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Regiao
0,34750,2023-01-01,Rio De Janeiro,Notebook HP,3200.0,1,Cliente_9014,3200.0,Presencial,Sudeste
1,13699,2023-01-01,Rio De Janeiro,Teclado MecÃ¢nico,250.0,1,Cliente_24330,250.0,Presencial,Sudeste
2,81394,2023-01-01,Porto Alegre,Teclado MecÃ¢nico,250.0,1,Cliente_9758,250.0,Presencial,Sul
3,251,2023-01-01,São Paulo,Teclado MecÃ¢nico,250.0,3,Cliente_22822,750.0,Presencial,Sudeste
4,77068,2023-01-01,Rio De Janeiro,Notebook Dell,3500.0,1,Cliente_554,3500.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
99995,43207,2024-12-30,Belo Horizonte,Notebook Dell,3500.0,2,Cliente_15893,7000.0,Presencial,Sudeste
99996,3183,2024-12-30,Salvador,Mouse Gamer,120.0,1,Cliente_4075,120.0,Presencial,Nordeste
99997,9461,2024-12-30,Porto Alegre,Teclado MecÃ¢nico,250.0,1,Cliente_22763,250.0,Presencial,Sul
99998,2793,2024-12-30,Salvador,Notebook Dell,3500.0,1,Cliente_24692,3500.0,Presencial,Nordeste
99999,91693,2024-12-30,São Paulo,iPhone 14,5500.0,1,Cliente_17362,5500.0,Presencial,Sudeste

In [4]:
#Análise por agrupamento
#Ranking de faturamento por Loja

analise_por_loja = df_analise[['Loja', 'Faturamento']].groupby("Loja").sum().reset_index()
analise_por_loja = analise_por_loja.sort_values(by='Faturamento', ascending=False).reset_index(drop=True)
analise_por_loja['Faturamento'] = analise_por_loja['Faturamento'].map('R${:,.2f}'.format)
display(analise_por_loja)

             Loja      Faturamento
0        Salvador  R$42,300,610.00
1  Rio De Janeiro  R$42,294,720.00
2          Recife  R$42,190,390.00
3       São Paulo  R$42,090,690.00
4  Belo Horizonte  R$41,714,890.00
5    Porto Alegre  R$41,678,460.00
6        Curitiba  R$41,121,720.00
7          Online   R$6,080,850.00

In [5]:
#Ranking produtos que mais venderam no online
df_vendas_online = df_analise[df_analise['Loja'] == 'Online']
analise_produtos_online = df_vendas_online[['Produto', 'Qtd']].groupby('Produto').sum().reset_index()
analise_produtos_online = analise_produtos_online.sort_values(by='Qtd', ascending=False).reset_index(drop=True)
analise_produtos_online = analise_produtos_online.rename(columns={'Qtd': 'Vendas Totais'})
display(analise_produtos_online)
display(df_vendas_online)

#Análise Rankin por loja e por produto
#Quais produtos venderam mais em cada uma das lojas?
analise_produtos_loja = df_analise[['Loja', 'Produto', 'Qtd']].groupby(['Loja', 'Produto']).sum()
analise_loja_produto = df_analise[['Loja', 'Produto', 'Qtd']].groupby(['Produto', 'Loja']).sum()
display(analise_produtos_loja)
display(analise_loja_produto)

              Produto  Vendas Totais
0         Notebook HP            442
1           Cabo HDMI            403
2           iPhone 14            390
3         Mouse Gamer            379
4       Notebook Dell            369
5   Teclado MecÃ¢nico            343
6         Monitor 27"            332
7  Smartphone Samsung            311

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Regiao
21,42190,2023-01-01,Online,Notebook Dell,3500.0,1,Cliente_20957,3500.0,Online,Online
84,71409,2023-01-01,Online,Smartphone Samsung,2200.0,1,Cliente_13248,2200.0,Online,Online
150,81764,2023-01-02,Online,Notebook Dell,3500.0,1,Cliente_9372,3500.0,Online,Online
164,84361,2023-01-02,Online,Notebook HP,3200.0,2,Cliente_16773,6400.0,Online,Online
251,37480,2023-01-02,Online,Notebook HP,3200.0,5,Cliente_1678,16000.0,Online,Online
...,...,...,...,...,...,...,...,...,...,...
99843,95096,2024-12-29,Online,iPhone 14,5500.0,1,Cliente_25495,5500.0,Online,Online
99898,8028,2024-12-30,Online,Smartphone Samsung,2200.0,1,Cliente_20679,2200.0,Online,Online
99913,38943,2024-12-30,Online,Notebook HP,3200.0,1,Cliente_18490,3200.0,Online,Online
99963,42794,2024-12-30,Online,Notebook HP,3200.0,1,Cliente_1868,3200.0,Online,Online
99983,55643,2024-12-30,Online,Mouse Gamer,120.0,2,Cliente_20362,240.0,Online,Online

                                    Qtd
Loja           Produto
Belo Horizonte Cabo HDMI           2636
               Monitor 27"         2625
               Mouse Gamer         2465
               Notebook Dell       2654
               Notebook HP         2775
...                                 ...
São Paulo      Notebook Dell       2535
               Notebook HP         2592
               Smartphone Samsung  2476
               Teclado MecÃ¢nico   2589
               iPhone 14           2735

[64 rows x 1 columns]

                           Qtd
Produto   Loja
Cabo HDMI Belo Horizonte  2636
          Curitiba        2698
          Online           403
          Porto Alegre    2571
          Recife          2534
...                        ...
iPhone 14 Porto Alegre    2540
          Recife          2652
          Rio De Janeiro  2702
          Salvador        2671
          São Paulo       2735

[64 rows x 1 columns]

In [6]:
import pandas as pd
import numpy as np

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Pandas: 2.3.1
NumPy: 2.3.2

In [2]:
print("Notebook funcionando!")

Notebook funcionando!